image: eclipse-temurin:21

stages:
  - build

before_script:
  - mkdir -p $HOME/.m2
  - echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"><servers><server><id>nexus.terrestris.de-releases-berlin</id><username>${NEXUS_USER}</username><password>${NEXUS_PASSWORD}</password></server><server><id>nexus.terrestris.de-snapshots-berlin</id><username>${NEXUS_USER}</username><password>${NEXUS_PASSWORD}</password></server></servers></settings>' > $HOME/.m2/settings.xml
  - ./mvnw -v || true

build-images:
  stage: build
  only:
    - main
  tags: ['intranet']
  script:
    - docker login -u $NEXUS_USER -p $NEXUS_PASSWORD gdi-berlin-docker.terrestris.de
    - ./mvnw -B install jib:build
    - docker push gdi-berlin-docker.terrestris.de/gdi-berlin/mde-backend
